### ISSUE TITLE
WebDriverAgent project is unable to build(find) the AppleTV( tvOS-17.2 Beta version

### ISSUE THREAD

**Issue by Chetantn** [appium/WebDriverAgent#807] opened 2023-11-07 12:17 UTC
Current Behavior
I'm working with latest AppleTV 4k upgraded with beta version i.e 17.2 tvOS(real device) , on which we execute some automated tests using appium for some of our in-house app's

when i'm trying to build the tvOS webDriverAgent project with below command( running from webdriver agent default project path) it is throwing following error.

command :
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination
'id=4d61282d6871dd9006c73a8e7e8f20298ed82e00' test
response:
Ineligible destinations for the "WebDriverAgentRunner_tvOS" scheme:
{ platform:tvOS, id:4d61282d6871dd9006c73a8e7e8f20298ed82e00, name:Living Room, error:Living Room’s tvOS 17.0 doesn’t match WebDriverAgentRunner_tvOS.xctest’s tvOS 17.2 deployment target. Upgrade Living Room’s tvOS version or lower WebDriverAgentRunner_tvOS.xctest’s deployment target. }

Note: I'm able to successfully build the tvos webDriverAgentLib_tvOS and webDriverAgentRunner_tvOS tvOS runner from Xcode, no error for Target devices there i have set it to 17.2 image attached

![image](https://github.com/appium/WebDriverAgent/assets/62075128/fb0c6cdb-de21-4380-b05e-8814ee5fb9e9)

but when i tried to run the command xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination 'id=4d61282d6871dd9006c73a8e7e8f20298ed82e00' test, it is complaining about deployment target.

Even i tried to set the tvOS deployment target to 17.0 and build the i had below issue which was expected because my AppleTV is deployed with 17.2 version
when u tried to run above command by downgrading the target got below response:

Response Logs :
2023-11-07 13:25:40.722 xcodebuild[19962:485925] DTDeviceKit: Started connection with 00008020-0011188A1A50003A
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ id:4d61282d6871dd9006c73a8e7e8f20298ed82e00 }

Available destinations for the "WebDriverAgentRunner_tvOS" scheme:
{ platform:tvOS, id:dvtdevice-DVTiOSDevicePlaceholder-appletvos:placeholder, name:Any tvOS Device }
{ platform:tvOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-appletvsimulator:placeholder, name:Any tvOS Simulator Device }

Expected Behavior
since i'm using all the latest drivers, plugin's, appium , xcode and macos it should build the tvOS webdriverAgent properly. since i'm able to launch the app for iphone with 17.1 os version with the same setup.

Minimal Reproducible Example
xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner_tvOS -destination 'id=4d61282d6871dd9006c73a8e7e8f20298ed82e00' test

Environment
and i have the following versions installed on mac, all are almost latest and some are beta version's too.

MAC ----SONOMA 14.1
XCODE --- 15.1 beta (15C5042i)
Appium --- 2.2.1 CLI version
✔ Listing installed plugins for appium
[execute-driver@3.0.19](mailto:execute-driver@3.0.19) [installed (npm)]
✔ Listing available drivers for appium
[uiautomator2@2.34.0](mailto:uiautomator2@2.34.0) [installed (npm)] [Up to date]
[xcuitest@5.8.1](mailto:xcuitest@5.8.1) [installed (npm)] [Up to date]
mac2 [not installed]
espresso [not installed]
safari [not installed]
gecko [not installed]
chromium [not installed]
NPM version ---8.15.0
NODE version --v16.17.1
Real Device --AppleTV 4k upgraded with beta version i.e 17.2 tvO
Link to Appium Logs
No response

Further Information
with this issue, want to know whether tvOS beta version is supported by latest webdriverAgent Project.

**Comment by KazuCocoa** [comment] 2023-11-07 17:22
Duplicate of https://github.com/appium/appium/issues/19381

`xcodebuild` itself was not able to detect the device, so `xcodebuild` command itself needs an update at least

**Closed as completed by KazuCocoa** 2023-11-07 17:22 UTC
