### ISSUE TITLE
Unable to inspect SwiftUI view embedded inside UITableView 

### ISSUE THREAD

**Issue by rahulnair199131** [appium/WebDriverAgent#957] opened 2024-11-18 15:45 UTC
We have been trying to migrate screens that were developed using UITool Kit to SwiftUI. In the process we have some screens that have SwiftUI embedded inside the UITool kit view. Our developers have defined accessibility ids for all elements in these views and these are inspectable using the native iOS xcode inspector. However when i try inspecting it with the appium inspector i get an empty list with no elements in the hierarchy tree. Attaching a screenshot of the element when inspecting through the native xcode accessibility inspector,

Attaching a screenshot of the same screen when inspected through the appium inspector,

I get the same response attached above when i try inspecting the app using the native Xcode accessibility inspector after WebDriver agent is installed. 

**Appium Version - 2.12.1**
**WebDriver Agent - Latest version from the WeDriver agent repo**
**Simulator OS - 18.1**
**Appium inspector version - 2023.12.2**

**Comment by KazuCocoa** [comment] 2024-11-18 17:20
Duplicate of https://github.com/appium/appium/issues/20759

**Closed as completed by KazuCocoa** 2024-11-18 17:20 UTC
