### ISSUE TITLE
运行WebDriverAgent后出现的Automation Running hold both volume buttons to stop 提示蒙层能否去掉

### ISSUE THREAD

**Issue by LiuShuai66** [appium/WebDriverAgent#883] opened 2024-04-01 12:06 UTC
运行WebDriverAgent后出现的Automation Running hold both volume buttons to stop 提示蒙层能否去掉

**Comment by LiuSky** [comment] 2024-04-02 00:53
No

**Comment by KazuCocoa** [comment] 2024-04-02 17:18
Duplicate of https://github.com/appium/appium/issues/19949

**Closed as completed by KazuCocoa** 2024-04-02 17:18 UTC
