### ISSUE TITLE
WebDriverAgent not building in xcode 16.1. error: Cyclic dependency in module 'DarwinFoundation': DarwinFoundation -> _stddef -> DarwinFoundation

### ISSUE THREAD

**Issue by sandy-tpp** [appium/WebDriverAgent#949] opened 2024-11-03 16:52 UTC
I'm running Appium session with iOS emulator with xocde 16.1. There is error running xcodebuild. Below is the error logs (attached full log file)

`[d704a883][XCUITestDriver@1464] Beginning test with command 'xcodebuild build-for-testing test-without-building -project /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ED18BCAD-9713-4962-B4EE-E3F23A36B1DD IPHONEOS_DEPLOYMENT_TARGET=17.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO' in directory '/Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent'
[d704a883][XCUITestDriver@1464] Output from xcodebuild will be logged. To change this, use 'showXcodeLog' desired capability
[d704a883][Xcode] Command line invocation:
[d704a883][XCUITestDriver@1464] Waiting up to 60000ms for WebDriverAgent to start
[d704a883][XCUITestDriver@1464] Matched '/status' to command name 'getStatus'
[d704a883][XCUITestDriver@1464] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[d704a883][Xcode]     /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild build-for-testing test-without-building -project /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination id=ED18BCAD-9713-4962-B4EE-E3F23A36B1DD IPHONEOS_DEPLOYMENT_TARGET=17.5 GCC_TREAT_WARNINGS_AS_ERRORS=0 COMPILER_INDEX_STORE_ENABLE=NO
[d704a883][Xcode] 
[d704a883][Xcode] User defaults from command line:
[d704a883][Xcode]     IDEPackageSupportUseBuiltinSCM = YES
[d704a883][Xcode] 
[d704a883][Xcode] Build settings from command line:
[d704a883][Xcode]     COMPILER_INDEX_STORE_ENABLE = NO
[d704a883][Xcode]     GCC_TREAT_WARNINGS_AS_ERRORS = 0
[d704a883][Xcode]     IPHONEOS_DEPLOYMENT_TARGET = 17.5
[d704a883][Xcode] 
[d704a883][XCUITestDriver@1464] connect ECONNREFUSED 127.0.0.1:8100
[d704a883][Xcode] --- xcodebuild: WARNING: Using the first of multiple matching destinations:
[d704a883][Xcode] { platform:iOS Simulator, id:ED18BCAD-9713-4962-B4EE-E3F23A36B1DD, OS:17.5, name:iPhone 15 Pro Max }
[d704a883][Xcode] { platform:iOS Simulator, id:ED18BCAD-9713-4962-B4EE-E3F23A36B1DD, OS:17.5, name:iPhone 15 Pro Max }
[d704a883][Xcode] Prepare packages
[d704a883][Xcode] 
[d704a883][Xcode] ComputeTargetDependencyGraph
[d704a883][XCUITestDriver@1464] Parsed BUILD_DIR configuration value: '/Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/build'
[d704a883][XCUITestDriver@1464] Got derived data root: '/Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules'
[d704a883][Xcode] note: Building targets in dependency order
[d704a883][Xcode] note: Target dependency graph (2 targets)
[d704a883][Xcode]     Target 'WebDriverAgentRunner' in project 'WebDriverAgent'
[d704a883][Xcode]         ➜ Explicit dependency on target 'WebDriverAgentLib' in project 'WebDriverAgent'
[d704a883][Xcode]     Target 'WebDriverAgentLib' in project 'WebDriverAgent' (no dependencies)
[d704a883][Xcode] 
[d704a883][Xcode] GatherProvisioningInputs
[d704a883][Xcode] 
[d704a883][Xcode] CreateBuildDescription
[d704a883][Xcode] 
[d704a883][Xcode] ClangStatCache /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1 -22B74-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache
[d704a883][Xcode]     cd /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgent.xcodeproj
[d704a883][Xcode]     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang-stat-cache /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk -o /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1-22B74-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache
[d704a883][XCUITestDriver@1464] Matched '/status' to command name 'getStatus'
[d704a883][XCUITestDriver@1464] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[d704a883][XCUITestDriver@1464] connect ECONNREFUSED 127.0.0.1:8100
[d704a883][Xcode] 
[d704a883][Xcode] ScanDependencies Analyze /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/RoutingHTTPServer/RouteResponse.m normal arm64 (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
[d704a883][Xcode]     cd /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent
[d704a883][Xcode]     
[d704a883][Xcode]     Using response file: /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgdtqzuuivxtkffbvuejlflbhewo/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/arm64/22a6d426986e98cf1a8e0c880c6a22df-common-args.resp
[d704a883][Xcode]     
[d704a883][Xcode]     builtin-ScanDependencies -o /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgdtqzuuivxtkffbvuejlflbhewo/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/StaticAnalyzer/WebDriverAgent/WebDriverAgentLib/normal/arm64/RouteResponse.plist.scan -- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -ivfsstatcache /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphonesimulator18.1-22B74-3d93aac3a03ebac1dd8474c5def773dc.sdkstatcache -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -fno-color-diagnostics -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=/Users/santhoshkumar/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -Wmissing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wunreachable-code -Wquoted-include-in-framework-header -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Warc-repeated-use-of-weak -Wno-arc-maybe-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wunused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wshadow -Wno-four-char-constants -Wconversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wfloat-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wassign-enum -Wsign-compare -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -Wno-implicit-fallthrough -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -Wno-partial-availability -Wno-declaration-after-statement -Wno-objc-messaging-id -Wno-direct-ivar-access -Wno-cast-qual -Wno-deprecated-declarations -Weverything -Wno-objc-missing-property-synthesis -Wno-unused-macros -Wno-disabled-macro-expansion -Wno-gnu-statement-expression -Wno-language-extension-token -Wno-overriding-method-mismatch -Wno-missing-variable-declarations -Wno-auto-import -Wno-objc-interface-ivars -Wno-documentation-unknown-command -Wno-reserved-id-macro -Wno-unused-parameter -Wno-gnu-conditional-omitted-operand -Wno-explicit-ownership-type -Wno-date-time -Wno-cast-align -Wno-cstring-format-directive -Wno-double-promotion -Wno-partial-availability -Wno-objc-messaging-id -Wno-direct-ivar-access -Wno-cast-qual -Wno-declaration-after-statement @/Users/santhoshkumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgdtqzuuivxtkffbvuejlflbhewo/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/Objects-normal/arm64/22a6d426986e98cf1a8e0c880c6a22df-common-args.resp -MMD -MT dependencies -MF /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgdtqzuuivxtkffbvuejlflbhewo/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/StaticAnalyzer/WebDriverAgent/WebDriverAgentLib/normal/arm64/RouteResponse.d --analyze /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/RoutingHTTPServer/RouteResponse.m -o /Users/santhoshkumar/Library/Developer/Xcode/DerivedData/WebDriverAgent-bgdtqzuuivxtkffbvuejlflbhewo/Build/Intermediates.noindex/WebDriverAgent.build/Debug-iphonesimulator/WebDriverAgentLib.build/StaticAnalyzer/WebDriverAgent/WebDriverAgentLib/normal/arm64/RouteResponse.plist
[d704a883][XCUITestDriver@1464] Matched '/status' to command name 'getStatus'
[d704a883][XCUITestDriver@1464] Proxying [GET /status] to [GET http://127.0.0.1:8100/status] with no body
[d704a883][XCUITestDriver@1464] connect ECONNREFUSED 127.0.0.1:8100
[d704a883][Xcode] /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stddef.h:64:10: error: Cyclic dependency in module 'DarwinFoundation': DarwinFoundation -> _stddef -> DarwinFoundation (in target 'WebDriverAgentLib' from project 'WebDriverAgent')
[d704a883][Xcode]     /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/RoutingHTTPServer/RouteResponse.h:1:9: note: while building module 'Foundation' imported from /Users/santhoshkumar/.appium/node_modules/appium-xcuitest-driver/node_modules/appium-webdriveragent/WebDriverAgentLib/Vendor/RoutingHTTPServer/RouteResponse.h:1:
[d704a883][Xcode]     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: note: while building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
[d704a883][Xcode]     /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:10: note: while building module 'sys_types' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator18.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:18:
`
[appium-logs.txt](https://github.com/user-attachments/files/17611266/appium-logs.txt)

**Comment by KazuCocoa** [comment] 2024-11-04 07:55
Duplicate of https://github.com/appium/appium/issues/20723

**Closed as completed by KazuCocoa** 2024-11-04 07:55 UTC
