### ISSUE TITLE
Query - WebDriverAgent install prompts for passcode / Touch ID to Enable UI Automation

### ISSUE THREAD

**Issue by Reeta-L** [appium/WebDriverAgent#804] opened 2023-11-02 10:31 UTC
When doing UI automation, WebDriverAgent is installed and it prompts for passcode/ Touch Id to "Enable UI Automation". Then it works for some hours or days, but after some time it prompts again, even when WebDriverAgent is already installed. "Enable UI Automation" is already enabled in "Settings" - "Developer" menu.
The devices are located remotely and we can't access them directly, so this is a big issue for us right now. Removing the passcode is no valid workaround since we have apps that require the passcode to start.

Why it is random even when "Enable UI Automation" is already enabled and WebDriverAgent is already installed or no change.

**Comment by KazuCocoa** [comment] 2023-11-02 19:05
Duplicate of https://github.com/appium/appium/issues/19363
This is a limitation by Apple for XCTest for UI process.

**Closed as completed by KazuCocoa** 2023-11-02 19:05 UTC
