### ISSUE TITLE
Software keyboard won't be shown when using `isHeadless: true` after `fb_clearTextWithSnapshot` is called

### ISSUE THREAD

**Issue by ppken** [appium/WebDriverAgent#951] opened 2024-11-05 02:16 UTC
When using headless mode with xcode 16 and simulator, software keyboard won't be shown after `fb_clearTextWithSnapshot` is called. (In headful mode, the problem didn't occur.)

As far as I checked, [this text clear logic](https://github.com/appium/WebDriverAgent/blob/v8.9.4/WebDriverAgentLib/Categories/XCUIElement%2BFBTyping.m#L172-L175) is causing this problem since when I removed it, software keyboard was shown even after `fb_clearTextWithSnapshot` was called.

Is it ok to send a PR not to use above text clear logic in xcode 16 (or later)? 

## [Headless mode]
![screen_headless](https://github.com/user-attachments/assets/05bf60f7-9212-4549-9884-e569eb5c8a2a)

## [Headful mode]
![screen_headful](https://github.com/user-attachments/assets/2bea3c92-df5c-47e6-a6da-5d925d8e3bc0)

**Comment by KazuCocoa** [comment] 2024-11-06 05:40
Duplicate of https://github.com/appium/appium/issues/20727

**Closed as completed by KazuCocoa** 2024-11-06 05:40 UTC
