### ISSUE TITLE
Fail to run on real device

### ISSUE THREAD

**Issue by rikyzan** [appium/WebDriverAgent#320] opened 2020-04-29 17:07 UTC
Hi, 
i'm trying to run WebDriverAgentRunner on my iPhone XR, but i'm encountering some error, and i can't understand why

Environment:
Xcode 11.3.1
IOS 13.3.1
Appium 1.15.1
MacOS 10.15.4

i followed the full manual configuration at http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ but when i type and run 
`xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner -destination 'id=<udid>' test`
this error appears:
```
Testing failed:
	WebDriverAgentRunner:
		WebDriverAgentRunner-Runner.app (797) encountered an error (Failed to load the test bundle. (Underlying error: Impossibile caricare il pacchetto “WebDriverAgentRunner” perché è danneggiato o privo delle risorse necessarie. Il pacchetto è danneggiato o privo delle risorse necessarie. dlopen_preflight(/var/containers/Bundle/Application/3BECB721-0CAB-4A23-A53B-46BEE8E13809/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner): no suitable image found.  Did find:
	/var/containers/Bundle/Application/3BECB721-0CAB-4A23-A53B-46BEE8E13809/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner: code signature invalid for '/var/containers/Bundle/Application/3BECB721-0CAB-4A23-A53B-46BEE8E13809/WebDriverAgentRunner-Runner.app/PlugIns/WebDriverAgentRunner.xctest/WebDriverAgentRunner'
))

** TEST FAILED **
```
It seems to be a provisioning/certificates problem, but from Xcode no issues are shown when i build IntegrationApp and WebDriverAgentRunner. 
I tried to use a simulator with the same specifics and xcodebuild command run without problems.

Could anyone help me?
Thanks

Ps: I tried the same steps with project from npm distribution, project inside Appium Desktop and webdriveragent-xcode_11.3.1 downloaded from this repo, same error appears

**Comment by KazuCocoa** [comment] 2020-05-01 16:02
How did you configure with manual or automatic?
I wondered how did you configure your provisioning profile.

Btw, how about `xcodeOrgId`, `xcodeSigningId` and `updatedWDABundleId` via Appium?

**Comment by rikyzan** [comment] 2020-05-01 19:39
Thank you for reply @KazuCocoa 

I used the "Automatically manage signing option" of Xcode, with two different setting
* IntegrationApp and WebDriverAgentRunner with new unique bundle ids (xxx.yyy.IntegrationApp and xxx.yyy.WebDriverAgentRunner)
* IntegrationApp (xxx.yyy.IntegrationApp), WebDriverAgentRunner (xxx.yyy.WebDriverAgentRunner) and WebDriverAgentLib (original bundle id)

same errors occurs

without `xcodebuild` command success i'm unable to install WebDriverAgentRunner and appium always fails

There's something like option or flag that is missing or wrong in my xcode setting?

**Comment by KazuCocoa** [comment] 2020-05-02 01:25
afaik, `.xctrunner` bundle id for test may be related to. I've appended the last line in the below troubleshooting (it is not reflected to appium.io)
https://github.com/appium/appium/blob/master/docs/en/drivers/ios-xcuitest-real-devices.md#troubleshooting-ideas
Xcode seems to handle it well, but we probably tweak it without Xcode (like vanilla xcodebuild)

**Comment by rikyzan** [comment] 2020-05-02 10:09
unfortunately Xcode seems to work well, because it generates something like `xxx.WebDriverAgentRunner.xctrunner`. if i append `.xctrunner` in bundle id, in log i could see the generated bundle is `xxx.WebDriverAgentRunner.xctrunner.xctrunner`.

could i use other workarounds for installing WDA? thanks @KazuCocoa

**Comment by KazuCocoa** [comment] 2020-05-03 02:12
I mean creating a profile for a bundle id with `.xctrunner`.
If you could not use wildcard one, potentially the `.xctrunner` may help to create a proper provisioning profile.

I always do below either way to run appium against a real device.

- xcodeOrgId, xcodeSigningId and updatedWDABundleId as Appium's capabilities

or

- Open WebDriverAgent.xcodeproj and configure automatic provisioning profile, then launch Appium ( as  http://appium.io/docs/en/drivers/ios-xcuitest-real-devices/ )
<img src=https://user-images.githubusercontent.com/5511591/80896812-6245ae80-8d2d-11ea-9e5a-7654918dee92.png width=300>


I faced a couple of errors with a personal account (in a year), but no errors with a paid account.
A personal account may also have an issue to handle well in xcodebuild.
(In the case, Xcode also had an issue in my case)

**Comment by rikyzan** [comment] 2020-05-04 16:59
Hi @KazuCocoa,

Today WebDriverAgent worked!! I used a paid account (in last days I used a personal one)

I made these steps:
* pic a new webdriveragent project
* run `mkdir [..]` and `bootstrap` as shown in doc (http://appium.io/docs/en/drivers/ios-xcuitest-real-devices)
* from Xcode, enable "Automatically manage signing" and update bundle ids of IntegrationApp and WebDriverAgentRunner
* then `xcodebuild [..]`  command from shell

first time, with a paid account, I had success. Then, I made exactly the same steps with a personal (using a new project and new bundle ids) but I encountered the same error like in the first post, `code signature invalid`.

My env is 
Xcode 11.3.1
Mac OS Catalina 10.15.4
iOS 13.3.1
Appium 1.15.1

Do you know if is possible using a personal account actually? In a previous version of env (Xcode 10.1 and iOS 12.4) I did.

Thank you very much for supporting me :) !

**Comment by mykola-mokhnach** [comment] 2020-05-04 17:02
Could be a duplicate of https://github.com/appium/appium/issues/13927

**Comment by KazuCocoa** [comment] 2020-05-04 17:09
I don't have an exact answer for the personal account question, unfortunately.
Some persons said when they re-create a new account, it succeeded. Only Apple knows the root cause...

**Closed as completed** 2020-05-04 17:10 UTC
